import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import styled from "styled-components";
import { FeedsList } from "../data";
const ListComponents = styled.section`
  img {
    width: 100%;
  }
  li {
    list-style-type: none;
    padding: 0;
  }
  figure {
    margin: 0;
    img {
      width: 55px;
    }
  }
  width: 100%;
`;
const Feeds: NextPage = () => {
  console.log("aa", FeedsList);
  const [FList, setFLst] = useState(FeedsList);
  return (
    <section>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <ListComponents>
        <ul>
          {FList.map((item, key) => (
            <li key={key}>
              <figure>
                <figcaption>
                  <img src={item.profile.thumbnail} alt="profile image" />
                  <span> {item.profile.name}</span>
                  <div>
                    {item.profile.tagList.map((tag, tagKey) => {
                      <button key={tagKey}>{tag.name}</button>;
                    })}
                  </div>
                </figcaption>
              </figure>
              <dl>
                <dt>
                  <img src={item.thumbmail} alt="thumbnail" />
                  <div>
                    {item.tagList.map((tag, tagKey) => {
                      <button key={tagKey}>{tag.name}</button>;
                    })}
                  </div>
                  <h2>{item.title}</h2>
                </dt>
                <dd>
                  <h3>{item.contents}</h3>
                </dd>
                <div>
                  <div>
                    <button>{item.status}</button>
                  </div>
                  <div>
                    <button>북마크버튼</button>
                    <button>공유하기</button>
                  </div>
                </div>
              </dl>
            </li>
          ))}
        </ul>
      </ListComponents>
    </section>
  );
};

export default Feeds;
